pgj/freebsd-wifibox

README.md
Document that the current version of the code has been tested on the following configurations (successfully):
- 13.2-RELEASE
- 14.0-BETA3
- 15-CURRENT (snapshot of `20230907`)
Furthermore, generalize the text about the officially unsupported versions.
=> docs(README): update test configuration data

man/wifibox.8
Note that this only has effect if the guest supports that and it is enabled there.
This is related to #63.
=> docs(man): include information about IPv6 configuration

etc/bhyve.conf.sample, sbin/wifibox
Sometimes it might be necessary to work with multiple pass-through devices.  For example, when the guest wants to talk to the Bluetooth controller of the wireless device and this requires the communication with the USB xHCI controller as well.
Allow the `passthru` configuration option in `bhyve.conf` to hold multiple PCI device slot/bus/function values.  This extension is backward compatible.
=> feat: add support for configuring multiple PCI pass-through devices

Makefile, README.md, sbin/wifibox
It was a promising experiment but it did not seem to be important enough to get continuous support and development.  Now, that FreeBSD 12 has reached its end-of-life, there is no strict need for this utility.  Remove the corresponding configuration parameters for the sake of simplicity.
Note that each of the script variable that controls the location of the respective `bhyve` component could still be overridden from the environment.
=> feat: sunset `bhyve+` and FreeBSD 12 support

.github/ISSUE_TEMPLATE/bug-report.yml
It may not be evident for the users where the log level configuration could be found.  There is only a subtle reference for the location of the configuration files on the manual page, which may not be easy to spot.
=> fix(issue template): add hint for logging

sbin/wifibox
There was no check to ensure that the `passthru=` configuration option in the `bhyve.conf` file is in the expected format, but that was passed blindly through a sequence of commands.  Though the format is documented in the file, it cannot be safely assumed that it will be given properly, possibly by mistake.
At the same time, use this opportunity to provide a better error message for the user and cause less frustration.
Fixes #82
=> fix(`bhyve.conf`): add syntax check for PCI pass-through configuration

README.md, man/wifibox.8
Previously, it was not emphasized that Wifibox is not a drop-in replacement for the FreeBSD wireless networking stack, which could have created confusion and false expectations.  Add sentences to both the README and the manual page to clarify that this is not the case.
Add more pointers to `wifibox-guest(5)` for the manual page to help the users understand that the most part of the configuration actually depends on how the guest is constructed.
Recommend the user to verify the sample configuration before use, and place a hint on where to increase a logging verbosity for diagnostics.
Fixes #83
=> docs: make documentation more explicit on certain details

sbin/wifibox
It is not always the case that the kernel modules are located under the `/boot/kernel` directory.  For custom kernels, that is something else (though usually somewhere within `/boot`) which makes the script fail to function properly.
On initialization, query the currently lodaded kernel itself about the path of its accompaining modules and use that information for finding `vmm(4)`.
Fixes #86
=> fix(`wifibox`): be more adaptive about the location of the `vmm` kernel module

README.md
Per user report, record the Intel AX210 as a wireless adapter that was confirmed to be working with Wifibox.  Also, since this happened on 13.3-RELEASE, update the `README` to prefer this version from the 13.x line of releases.
=> docs(`README`): add Intel AX210 as working hardware

etc/bhyve.conf.sample, sbin/wifibox
Currently, the guest is run with the same on priority level as any other process.  This does not always work well for handling the wireless traffic, since firewalling and other networking functions in the kernel are run with higher priorities.
Employ `nice(1)` to adjust the priority of the managed `bhyve` process that is responsible for running the virtualized guest, and expose its prority setting as a configuration value in `bhyve.conf`.  This value has its own scale, which independent from what `nice(1)` has in order to make it possible to replace this tool for others, e.g. `rtprio(1)` later on.
Suggested by: [Anton Saietskii](mailto:vsasjason@gmail.com)
=> feat(`bhyve.conf`): configurable priority of the `bhyve` process

sbin/wifibox
It is not ensured that elements of the `bhyve` configuration are in either the expected format or range.  This is going to show up sooner or later and stop the guest from working, but it is more friendly if these mistakes are reported directly to the user.
This commit is inspired by 221b2c07.
=> feat(`bhyve.conf`): input validation

README.md
Confirm that the recent version of Wifibox works on the following FreeBSD version:
- 13.3-RELEASE
- 14.0-RELEASE
- 15.0-CURRENT, snapshot of 2024-03-14
=> docs: update FreeBSD versions for my configuration

README.md
Include another configuration that was reported to be working.
=> chore(`docs`): add Carbon X1 + Intel Wireless AC 9560 as working configuration

README.md
Per user report, record that Wifibox on Dell Precision 7720 works on FreeBSD 14.1-RELEASE too.
=> docs(`README`): add one more tested release for Dell Precision 7720

man/wifibox.8, sbin/wifibox
Character devices under the governance of the `nmdm(4)` driver are created on demand on first access therefore it does not make sense to check for their presence and remove them based on the response. Similarly, this behavior of null-modem devices makes it unncessary to create them explicitly before `wifibox` gets to use them.
In addition to that, removing existing `nmdm(4)` devices ahead of time externally causes the kernel module fail to unload.  This is clearly a bug in the base system itself, but let us reduce the chances and simplify the code of `wifibox` itself.
Remove both the `create_nmdm` and `destroy_nmdm` functions as well as the option to restart the console, as an attached functionality.
Fixes #104
=> feat(`wifibox`): remove explicit management of `nmdm(4)` devices

sbin/wifibox
Previously, a `kill -SIGTERM` would be requested of the daemon, which would forward the signal to /usr/local/sbin/wifibox. /usr/local/sbin/wifibox would not forward the signal to bhyve, which requires the signal to shutdown cleanly.
Also explicitly unlink the tap interface from the wifibox interface, and wait 5 seconds instead of 3 for the VM to shutdown.
Also consistently use subshells.
=> fix(`wifibox`): correctly terminate the VM by sending `SIGTERM`

README.md
This configuration was reported by [Gábor Záhemszky](mailto:gabor@zahemszky.hu).  While here, bump the latest release from the 14.x line to 14.1.
=> docs(`README`): add another working configuration

etc/bhyve.conf.sample, sbin/wifibox
The static 3-second timeout for waiting the guest on stop may not be enough for the guest to complete its shutdown sequence.  This can be important for letting the guest to run certain tear-down functions and prevent from leaving the hardware in an troublesome state.
Instead, after the `TERM` signal is sent to initiate the graceful termination of the guest, periodically check back on its state for a while (configurable by the user, defaults to 10 seconds) and either consider it stopped or make an attempt to forcefully stop the guest to avoid the infinite wait.
This is also some form of mitigation of the bug that was uncovered in 95312ad5.  Previously the forceful shutdown was always executed because the ACPI power-off did not work.  But with that change, it now often becomes unnecessary …
=> feat(`wifibox`): adaptively wait on stopping the guest

README.md
Include another Apple MacBook Pro in the list that was verified to be working.  It is based on the Broadcom BCM43602 chipset.  Reported by [Joshua Rogers](mailto:Joshua@Joshua.Hu).
=> docs(`README`): add MBP / BCM43602 to the list of working configurations

Makefile, README.md, man/wifibox.8
FreeBSD versions starting from 14.0 can now properly trigger the `suspend` action for `rc(8)` scripts [1] hence the workaround for that is no longer needed.  Implement an automated detection of this feature in the build process and lose the fix depending on the OS version.
Note that since the original change in `src` did not bump the `__FreeBSD_version`, it is not possible to tell exactly if the userland has the necessary support.  Thus an approximate version is used to err on the side of caution.  Fortunately, that is not a problem if the suspension logic is run twice, because that is idempotent.
Fixes #120
[1] https://github.com/freebsd/freebsd-src/commit/2cf8ef5910fd3754f8021f9c67fde6b9d9030f33
=> chore(`devd`): make inclusion of the configuration extension optional

devd/wifibox.conf.sample
Previously, the system would likely be suspended in the middle of the stopping of the VM (if using `RECOVER_SUSPEND_VMM` or `RECOVER_SUSPEND_GUEST` for example), meaning critical tasks like the removing of the PCI devices and unloading of the VMM module were executed after a _resume_, not before a suspension.
Also, remove the superfluous call to /etc/rc.suspend. By default, this script is executed by a devd rule of a lower priority _after_ this rule is executed.
=> fix(`wifibox`): ensure suspended before notifying the system to suspend

sbin/wifibox
On stopping the guest, a `TERM` signal is sent for the whole process group that was created for the VM manager.  This means that the VM manager is also stopped which should be taking care of destroying the corresponding VM.  In result, the VM is left behind and not cleaned up eventually.
Switch over to sending the `TERM` signal to the guest itself.  The VM manager will be notified of the guest stopping anyway, since `bhyve` is going to translate `TERM` to an ACPI power-off event. This would then gracefully let the manager to take care of the associated clean-up tasks, including destroy the VM.  At the same time, focus the guest itself to see if it is running, and do not care about the manager.
This is an alternative approach to implement #118.
=> fix(`wifibox`): send the `TERM` signal to the guest directly

etc/bhyve.conf.sample
Under certain circumstances, 10 seconds may not be enough.  Bump the time limit to a higher value just to provide a safe default value.
=> fix(`bhyve.conf`): increase the time limit for forced guest shutdowns

sbin/wifibox
The `ppt` driver cannot be cleared until the VM runs so move the respective `devctl(8)` call back to the end of `destroy_vm`. Restore the wait period after the VM is destroyed to make sure that the device is released.
More importantly, do not let `vm_stop` to call `destroy_vm` but leave it the VM manager to take care of the clean-up tasks.  The VM manager should be unblocked to do that after the guest either stops by itself (due to the ACPI power-off event) or forcefully stopped.  In addition to that, wait for the VM manager to stop too, because it should not be launched again (on a different thread) until all the clean-up tasks have been completed.
=> fix(`wifibox`): avoid race conditions on restarting the guest

sbin/wifibox
It is not guaranteed (although anticipated) that the guest will start up after a second.  Give 4 more seconds for the guest to do so, but quit waiting earlier if it is up.  After this time period, warn the user that the guest might not have started up.
=> fix(`wifibox`): adaptively wait for the guest to start up

README.md
Mark `13.4-RELEASE`, `14.1-RELEASE`, and `15.0-CURRENT` verified.  That is based on local testing.
=> chore(`README`): update the list of working FreeBSD versions

.github/workflows/man.yml, .github/workflows/shellcheck.yml, Makefile, man/wifibox.8
Configure an additional CI job to run some basic formatting and style checks on the changes to the manual page.  As part of that, address all the identified issues there so we could start with a clean slate.
At the same time, make running ShellCheck dependent on changes to the script itself, so it will not be run unless that is necessary.
=> chore(`workflows`): extend build checks to cover manual pages

README.md
While I'm here slightly update the name of ThinkPad X1 Carbon Gen5 for my previous entry.
=> Add Lenovo ThinkPad X1 Carbon Gen 9

README.md
After the presentation at EuroBSDcon 2024, I was invited to write an article on Wifibox for the [FreeBSD Journal](https://freebsdfoundation.org/our-work/journal/).  I accepted the opportunity and the article was published in the [November/December 2024 edition](https://freebsdfoundation.org/our-work/journal/browser-based-edition/virtualization-2/) of the journal, a special issue on Virtualization. This article is now being added as part of the documentation for the project.
=> docs: add the FreeBSD Journal article

sbin/wifibox
The `assert_kmod_loaded` function expects kernel modules to be loaded from a specified location and it fails to work if the module in question has been actually added to the kernel.  This case was not considered before because both `nmdm` and `vmm` are shipped as optional, loadable modules with the stock FreeBSD kernel, and that is usually not an issue.
Relax this restriction and allow working with built-in kernel modules.  This way users with customized kernels would be supported.  The original motivation behind this check is to ensure that the loadable modules are created for a compatible kernel. But that implicitly holds when they are included there.
Fixes #136
=> fix(`wifibox`): consider built-in kernel modules on checking their presence

sbin/wifibox
The `get_kmod_path()` function lets `kldstat(8)` emit its warning when details of a module is queried but it is built into the kernel, for example:
```console
kldstat: can't find file nmdm: No such file or directory
```
Mute all the error messages because only the return value is used and it is empty on errors anyway.
=> fix(`wifibox)`: silence `kldstat(8)` error messages on built-in modules

README.md
Mark 13.5-RELEASE, 14.2-RELEASE, and 15.0-CURRENT (as of the time of writing) verified.
=> chore(`README`): update verified versions
